### ISSUE TITLE
False positive errors

### ISSUE THREAD

**Issue by AlpTheTurkic** [cwtools/cwtools-hoi4-config#202] opened 2024-08-06 22:21 UTC
![Ekran Alıntısı](https://github.com/user-attachments/assets/221d772f-c6dc-4c16-9645-06ddffbfb374)
There are 4 thousand more fake errors like this.
![image](https://github.com/user-attachments/assets/ab52956b-78e0-4de5-89ab-0b18dff0cf86)
even sees what's happening in the game as an error

**Comment by Pelmen323** [comment] 2024-08-13 18:05
@AlpTheTurkic Try to regenerate vanilla cache first "View ->Command Palette-> regenerate vanilla cache"
If this doesn't help, we'll need more info, current report tells us nothing. Let's start with this - is this vanilla or not?

**Comment by Pelmen323** [comment] 2024-12-20 17:13
I'll close the issue - both traits error and portraits error are not reproducible
Vanilla is a mess atm due to not closed brackets and DLC files not properly supported, but at least reported errors are not valid with the latest config
Regenerate vanilla cache "View ->Command Palette-> regenerate vanilla cache" just in case

**Closed by Pelmen323** 2024-12-20 17:13 UTC
